---
- name: "Ensure `python_versions` is passed as argument"
  assert:
    that:
      - python_versions != ""
    msg: "'python_versions' must be passed as argument!!"


- name: Install with 'pyenv'
  include_tasks: with-pyenv.yml
  when: installation_method == "pyenv"

- name: Install with 'asdf'
  include_tasks: with-asdf.yml
  when: installation_method == "asdf"
